# this file was generated by doing
# to get the iso : vagrant box add centos/8
# to get the default vagrantfile : vagrant init --minimal

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "myhost"
  config.vm.network "private_network", ip: "192.168.50.10"
end
